import type { NextPage } from "next";
import Head from "next/head";
import HomeHeader from "~/components/home/homeHeader";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PrinTIC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/general/ticLogo.ico" />
      </Head>
      <HomeHeader />
      <main className=" flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-8xl text-[#FFF] font-spacemono">Home</h1>
      </main>
    </>
  );
}

export default Home;